# Generated by Django 4.2.16 on 2025-12-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DireccionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPersona',
            fields=[
                ('emppe_id', models.AutoField(primary_key=True, serialize=False)),
                ('emppe_rut', models.CharField(max_length=11, unique=True, verbose_name='RUT')),
                ('emppe_nom', models.CharField(max_length=100, verbose_name='Nombre o Razón Social')),
                ('emppe_alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias Comercial')),
                ('emppe_fono1', models.CharField(max_length=15, verbose_name='Teléfono principal')),
                ('emppe_fono2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono secundario')),
                ('emppe_mail1', models.EmailField(max_length=100, verbose_name='Correo principal')),
                ('emppe_mail2', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo secundario')),
                ('emppe_est', models.BooleanField(default=True, verbose_name='Activo')),
                ('emppe_sit', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('ambos', 'Cliente y Proveedor')], default='cliente', max_length=20, verbose_name='Situación')),
                ('emppe_dire', models.ForeignKey(blank=True, db_column='DIRE_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='DireccionApp.direccion', verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Empresa o Persona',
                'verbose_name_plural': 'Empresas y Personas',
                'db_table': 'EMPRESAPERSONA',
                'ordering': ['emppe_nom'],
                'managed': True,
            },
        ),
    ]
