# Generated by Django 4.2.16 on 2025-12-08 20:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmpresaPersonaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emppe', models.ForeignKey(db_column='EMPPE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='abastecimientos', to='EmpresaPersonaApp.empresapersona')),
            ],
            options={
                'verbose_name': 'Abastecimiento',
                'verbose_name_plural': 'Abastecimientos',
                'db_table': 'ABASTECIMIENTO',
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('produ_id', models.AutoField(primary_key=True, serialize=False)),
                ('produ_sku', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, números, espacios, puntos y guiones.', regex='^[A-Za-z0-9ÁÉÍÓÚáéíóúÑñ .\\-]+$')], verbose_name='SKU del producto/servicio')),
                ('produ_nom', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, números, espacios, puntos y guiones.', regex='^[A-Za-z0-9ÁÉÍÓÚáéíóúÑñ .\\-]+$')], verbose_name='Nombre del producto/servicio')),
                ('produ_desc', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, números, espacios, puntos y guiones.', regex='^[A-Za-z0-9ÁÉÍÓÚáéíóúÑñ .\\-]+$')], verbose_name='Descripción')),
                ('produ_bruto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor Bruto')),
                ('produ_neto', models.PositiveIntegerField(default=0, verbose_name='Valor Neto')),
                ('produ_iva', models.PositiveIntegerField(default=0, verbose_name='IVA (19%)')),
                ('produ_dscto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Descuento')),
                ('produ_vigencia_inicio', models.DateField(blank=True, help_text='Fecha mínima permitida para emitir o reclamar documentos asociados a este producto.', null=True, verbose_name='Vigencia desde')),
                ('produ_vigencia_fin', models.DateField(blank=True, help_text='Fecha máxima permitida para emitir o reclamar documentos asociados a este producto.', null=True, verbose_name='Vigencia hasta')),
                ('proveedores', models.ManyToManyField(related_name='productos_servicios', through='ProductoServicioApp.Abastecimiento', to='EmpresaPersonaApp.empresapersona', verbose_name='Proveedores asociados')),
            ],
            options={
                'verbose_name': 'Producto o Servicio',
                'verbose_name_plural': 'Productos y Servicios',
                'db_table': 'PRODUCTOS_SERVICIOS',
            },
        ),
        migrations.CreateModel(
            name='ProductoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='productos_excel/')),
                ('valor_neto', models.PositiveIntegerField(default=0)),
                ('valor_iva', models.PositiveIntegerField(default=0)),
                ('valor_bruto', models.PositiveIntegerField(default=0)),
                ('descuento', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_excel', to='ProductoServicioApp.productoservicio')),
            ],
            options={
                'db_table': 'PRODUCTO_EXCEL',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='produ',
            field=models.ForeignKey(db_column='PRODU_ID', on_delete=django.db.models.deletion.CASCADE, related_name='abastecimientos', to='ProductoServicioApp.productoservicio'),
        ),
        migrations.AlterUniqueTogether(
            name='abastecimiento',
            unique_together={('emppe', 'produ')},
        ),
    ]
