# Generated by Django 4.2.16 on 2025-12-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciuda_id', models.AutoField(primary_key=True, serialize=False)),
                ('ciuda_nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CIUDAD',
                'ordering': ['ciuda_nom'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comun_id', models.AutoField(primary_key=True, serialize=False)),
                ('comun_nom', models.CharField(max_length=50)),
                ('ciuda', models.ForeignKey(db_column='CIUDA_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comunas', to='DireccionApp.ciudad')),
            ],
            options={
                'db_table': 'COMUNA',
                'ordering': ['comun_nom'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regi_id', models.AutoField(primary_key=True, serialize=False)),
                ('regi_nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'REGION',
                'ordering': ['regi_nom'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('dire_id', models.AutoField(primary_key=True, serialize=False)),
                ('dire_calle', models.CharField(max_length=100)),
                ('dire_num', models.IntegerField()),
                ('dire_otros', models.CharField(blank=True, max_length=50, null=True)),
                ('dire_cod_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('ciuda', models.ForeignKey(db_column='CIUDA_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='DireccionApp.ciudad')),
                ('comun', models.ForeignKey(db_column='COMUN_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='DireccionApp.comuna')),
                ('regi', models.ForeignKey(db_column='REGI_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='DireccionApp.region')),
            ],
            options={
                'db_table': 'DIRECCION',
                'ordering': ['dire_id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='regi',
            field=models.ForeignKey(db_column='REGI_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciudades', to='DireccionApp.region'),
        ),
    ]
