# Generated by Django 4.2 on 2025-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciuda_id', models.AutoField(primary_key=True, serialize=False)),
                ('ciuda_nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CIUDAD',
                'ordering': ['ciuda_nom'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comun_id', models.AutoField(primary_key=True, serialize=False)),
                ('comun_nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'COMUNA',
                'ordering': ['comun_nom'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('dire_id', models.AutoField(primary_key=True, serialize=False)),
                ('dire_calle', models.CharField(max_length=100)),
                ('dire_num', models.IntegerField()),
                ('dire_otros', models.CharField(blank=True, max_length=50, null=True)),
                ('dire_cod_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
            ],
            options={
                'db_table': 'DIRECCION',
                'ordering': ['dire_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regi_id', models.AutoField(primary_key=True, serialize=False)),
                ('regi_nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'REGION',
                'ordering': ['regi_nom'],
                'managed': False,
            },
        ),
    ]
