from django.db import migrations


def seed_data(apps, schema_editor):
    Region = apps.get_model("DireccionApp", "Region")
    Ciudad = apps.get_model("DireccionApp", "Ciudad")
    Comuna = apps.get_model("DireccionApp", "Comuna")

    # ===========================
    # SEED: REGIONES
    # ===========================
    Region.objects.bulk_create([
        Region(regi_id=1, regi_nom='Arica y Parinacota'),
        Region(regi_id=2, regi_nom='Tarapacá'),
        Region(regi_id=3, regi_nom='Antofagasta'),
        Region(regi_id=4, regi_nom='Atacama'),
        Region(regi_id=5, regi_nom='Coquimbo'),
        Region(regi_id=6, regi_nom='Valparaíso'),
        Region(regi_id=7, regi_nom='Metropolitana de Santiago'),
        Region(regi_id=8, regi_nom="Libertador General Bernardo O'Higgins"),
        Region(regi_id=9, regi_nom='Maule'),
        Region(regi_id=10, regi_nom='Ñuble'),
        Region(regi_id=11, regi_nom='Biobío'),
        Region(regi_id=12, regi_nom='La Araucanía'),
        Region(regi_id=13, regi_nom='Los Ríos'),
        Region(regi_id=14, regi_nom='Los Lagos'),
        Region(regi_id=15, regi_nom='Aysén del General Carlos Ibáñez del Campo'),
        Region(regi_id=16, regi_nom='Magallanes y de la Antártica Chilena'),
    ])

    # ===========================
    # SEED: CIUDADES
    # ===========================
    Ciudad.objects.bulk_create([
        Ciudad(ciuda_id=1, ciuda_nom='Arica', regi_id=1),
        Ciudad(ciuda_id=2, ciuda_nom='Parinacota', regi_id=1),
        Ciudad(ciuda_id=3, ciuda_nom='Iquique', regi_id=2),
        Ciudad(ciuda_id=4, ciuda_nom='Tamarugal', regi_id=2),
        Ciudad(ciuda_id=5, ciuda_nom='Antofagasta', regi_id=3),
        Ciudad(ciuda_id=6, ciuda_nom='El Loa', regi_id=3),
        Ciudad(ciuda_id=7, ciuda_nom='Tocopilla', regi_id=3),
        Ciudad(ciuda_id=8, ciuda_nom='Copiapó', regi_id=4),
        Ciudad(ciuda_id=9, ciuda_nom='Chañaral', regi_id=4),
        Ciudad(ciuda_id=10, ciuda_nom='Huasco', regi_id=4),
        Ciudad(ciuda_id=11, ciuda_nom='Elqui', regi_id=5),
        Ciudad(ciuda_id=12, ciuda_nom='Choapa', regi_id=5),
        Ciudad(ciuda_id=13, ciuda_nom='Limarí', regi_id=5),
        Ciudad(ciuda_id=14, ciuda_nom='Valparaíso', regi_id=6),
        Ciudad(ciuda_id=15, ciuda_nom='Isla de Pascua', regi_id=6),
        Ciudad(ciuda_id=16, ciuda_nom='Los Andes', regi_id=6),
        Ciudad(ciuda_id=17, ciuda_nom='Petorca', regi_id=6),
        Ciudad(ciuda_id=18, ciuda_nom='Quillota', regi_id=6),
        Ciudad(ciuda_id=19, ciuda_nom='San Antonio', regi_id=6),
        Ciudad(ciuda_id=20, ciuda_nom='San Felipe de Aconcagua', regi_id=6),
        Ciudad(ciuda_id=21, ciuda_nom='Marga Marga', regi_id=6),
        Ciudad(ciuda_id=22, ciuda_nom='Santiago', regi_id=7),
        Ciudad(ciuda_id=23, ciuda_nom='Cordillera', regi_id=7),
        Ciudad(ciuda_id=24, ciuda_nom='Chacabuco', regi_id=7),
        Ciudad(ciuda_id=25, ciuda_nom='Maipo', regi_id=7),
        Ciudad(ciuda_id=26, ciuda_nom='Melipilla', regi_id=7),
        Ciudad(ciuda_id=27, ciuda_nom='Talagante', regi_id=7),
        Ciudad(ciuda_id=28, ciuda_nom='Cachapoal', regi_id=8),
        Ciudad(ciuda_id=29, ciuda_nom='Colchagua', regi_id=8),
        Ciudad(ciuda_id=30, ciuda_nom='Cardenal Caro', regi_id=8),
        Ciudad(ciuda_id=31, ciuda_nom='Talca', regi_id=9),
        Ciudad(ciuda_id=32, ciuda_nom='Cauquenes', regi_id=9),
        Ciudad(ciuda_id=33, ciuda_nom='Curicó', regi_id=9),
        Ciudad(ciuda_id=34, ciuda_nom='Linares', regi_id=9),
        Ciudad(ciuda_id=35, ciuda_nom='Diguillín', regi_id=10),
        Ciudad(ciuda_id=36, ciuda_nom='Itata', regi_id=10),
        Ciudad(ciuda_id=37, ciuda_nom='Punilla', regi_id=10),
        Ciudad(ciuda_id=38, ciuda_nom='Concepción', regi_id=11),
        Ciudad(ciuda_id=39, ciuda_nom='Arauco', regi_id=11),
        Ciudad(ciuda_id=40, ciuda_nom='Biobío', regi_id=11),
        Ciudad(ciuda_id=41, ciuda_nom='Cautín', regi_id=12),
        Ciudad(ciuda_id=42, ciuda_nom='Malleco', regi_id=12),
        Ciudad(ciuda_id=43, ciuda_nom='Valdivia', regi_id=13),
        Ciudad(ciuda_id=44, ciuda_nom='Ranco', regi_id=13),
        Ciudad(ciuda_id=45, ciuda_nom='Llanquihue', regi_id=14),
        Ciudad(ciuda_id=46, ciuda_nom='Chiloé', regi_id=14),
        Ciudad(ciuda_id=47, ciuda_nom='Osorno', regi_id=14),
        Ciudad(ciuda_id=48, ciuda_nom='Palena', regi_id=14),
        Ciudad(ciuda_id=49, ciuda_nom='Coyhaique', regi_id=15),
        Ciudad(ciuda_id=50, ciuda_nom='Aysén', regi_id=15),
        Ciudad(ciuda_id=51, ciuda_nom='Capitán Prat', regi_id=15),
        Ciudad(ciuda_id=52, ciuda_nom='General Carrera', regi_id=15),
        Ciudad(ciuda_id=53, ciuda_nom='Magallanes', regi_id=16),
        Ciudad(ciuda_id=54, ciuda_nom='Antártica Chilena', regi_id=16),
        Ciudad(ciuda_id=55, ciuda_nom='Tierra del Fuego', regi_id=16),
        Ciudad(ciuda_id=56, ciuda_nom='Última Esperanza', regi_id=16),
    ])

    # ===========================
    # SEED: COMUNAS
    # ===========================
    Comuna.objects.bulk_create([
        Comuna(comun_id=1, comun_nom='Arica', ciuda_id=1),
        Comuna(comun_id=2, comun_nom='Camarones', ciuda_id=1),
        Comuna(comun_id=3, comun_nom='General Lagos', ciuda_id=2),
        Comuna(comun_id=4, comun_nom='Putre', ciuda_id=2),
        Comuna(comun_id=5, comun_nom='Iquique', ciuda_id=3),
        Comuna(comun_id=6, comun_nom='Alto Hospicio', ciuda_id=3),
        Comuna(comun_id=7, comun_nom='Pozo Almonte', ciuda_id=4),
        Comuna(comun_id=8, comun_nom='Camiña', ciuda_id=4),
        Comuna(comun_id=9, comun_nom='Colchane', ciuda_id=4),
        Comuna(comun_id=10, comun_nom='Huara', ciuda_id=4),
        Comuna(comun_id=11, comun_nom='Pica', ciuda_id=4),
        Comuna(comun_id=12, comun_nom='Antofagasta', ciuda_id=5),
        Comuna(comun_id=13, comun_nom='Mejillones', ciuda_id=5),
        Comuna(comun_id=14, comun_nom='Sierra Gorda', ciuda_id=5),
        Comuna(comun_id=15, comun_nom='Taltal', ciuda_id=5),
        Comuna(comun_id=16, comun_nom='Calama', ciuda_id=6),
        Comuna(comun_id=17, comun_nom='Ollagüe', ciuda_id=6),
        Comuna(comun_id=18, comun_nom='San Pedro de Atacama', ciuda_id=6),
        Comuna(comun_id=19, comun_nom='Tocopilla', ciuda_id=7),
        Comuna(comun_id=20, comun_nom='María Elena', ciuda_id=7),
        Comuna(comun_id=21, comun_nom='Copiapó', ciuda_id=8),
        Comuna(comun_id=22, comun_nom='Caldera', ciuda_id=8),
        Comuna(comun_id=23, comun_nom='Tierra Amarilla', ciuda_id=8),
        Comuna(comun_id=24, comun_nom='Chañaral', ciuda_id=9),
        Comuna(comun_id=25, comun_nom='Diego de Almagro', ciuda_id=9),
        Comuna(comun_id=26, comun_nom='Vallenar', ciuda_id=10),
        Comuna(comun_id=27, comun_nom='Alto del Carmen', ciuda_id=10),
        Comuna(comun_id=28, comun_nom='Freirina', ciuda_id=10),
        Comuna(comun_id=29, comun_nom='Huasco', ciuda_id=10),
        Comuna(comun_id=30, comun_nom='La Serena', ciuda_id=11),
        Comuna(comun_id=31, comun_nom='Coquimbo', ciuda_id=11),
        Comuna(comun_id=32, comun_nom='Andacollo', ciuda_id=11),
        Comuna(comun_id=33, comun_nom='La Higuera', ciuda_id=11),
        Comuna(comun_id=34, comun_nom='Paihuano', ciuda_id=11),
        Comuna(comun_id=35, comun_nom='Vicuña', ciuda_id=11),
        Comuna(comun_id=36, comun_nom='Illapel', ciuda_id=12),
        Comuna(comun_id=37, comun_nom='Canela', ciuda_id=12),
        Comuna(comun_id=38, comun_nom='Los Vilos', ciuda_id=12),
        Comuna(comun_id=39, comun_nom='Salamanca', ciuda_id=12),
        Comuna(comun_id=40, comun_nom='Ovalle', ciuda_id=13),
        Comuna(comun_id=41, comun_nom='Combarbalá', ciuda_id=13),
        Comuna(comun_id=42, comun_nom='Monte Patria', ciuda_id=13),
        Comuna(comun_id=43, comun_nom='Punitaqui', ciuda_id=13),
        Comuna(comun_id=44, comun_nom='Río Hurtado', ciuda_id=13),
        Comuna(comun_id=45, comun_nom='Valparaíso', ciuda_id=14),
        Comuna(comun_id=46, comun_nom='Casablanca', ciuda_id=14),
        Comuna(comun_id=47, comun_nom='Concón', ciuda_id=14),
        Comuna(comun_id=48, comun_nom='Juan Fernández', ciuda_id=14),
        Comuna(comun_id=49, comun_nom='Puchuncaví', ciuda_id=14),
        Comuna(comun_id=50, comun_nom='Quintero', ciuda_id=14),
        Comuna(comun_id=51, comun_nom='Viña del Mar', ciuda_id=14),
        Comuna(comun_id=52, comun_nom='Isla de Pascua', ciuda_id=15),
        Comuna(comun_id=53, comun_nom='Los Andes', ciuda_id=16),
        Comuna(comun_id=54, comun_nom='Calle Larga', ciuda_id=16),
        Comuna(comun_id=55, comun_nom='Rinconada', ciuda_id=16),
        Comuna(comun_id=56, comun_nom='San Esteban', ciuda_id=16),
        Comuna(comun_id=57, comun_nom='La Ligua', ciuda_id=17),
        Comuna(comun_id=58, comun_nom='Cabildo', ciuda_id=17),
        Comuna(comun_id=59, comun_nom='Papudo', ciuda_id=17),
        Comuna(comun_id=60, comun_nom='Petorca', ciuda_id=17),
        Comuna(comun_id=61, comun_nom='Zapallar', ciuda_id=17),
        Comuna(comun_id=62, comun_nom='Quillota', ciuda_id=18),
        Comuna(comun_id=63, comun_nom='Calera', ciuda_id=18),
        Comuna(comun_id=64, comun_nom='Hijuelas', ciuda_id=18),
        Comuna(comun_id=65, comun_nom='La Cruz', ciuda_id=18),
        Comuna(comun_id=66, comun_nom='Nogales', ciuda_id=18),
        Comuna(comun_id=67, comun_nom='San Antonio', ciuda_id=19),
        Comuna(comun_id=68, comun_nom='Algarrobo', ciuda_id=19),
        Comuna(comun_id=69, comun_nom='Cartagena', ciuda_id=19),
        Comuna(comun_id=70, comun_nom='El Quisco', ciuda_id=19),
        Comuna(comun_id=71, comun_nom='El Tabo', ciuda_id=19),
        Comuna(comun_id=72, comun_nom='Santo Domingo', ciuda_id=19),
        Comuna(comun_id=73, comun_nom='San Felipe', ciuda_id=20),
        Comuna(comun_id=74, comun_nom='Catemu', ciuda_id=20),
        Comuna(comun_id=75, comun_nom='Llaillay', ciuda_id=20),
        Comuna(comun_id=76, comun_nom='Panquehue', ciuda_id=20),
        Comuna(comun_id=77, comun_nom='Putaendo', ciuda_id=20),
        Comuna(comun_id=78, comun_nom='Santa María', ciuda_id=20),
        Comuna(comun_id=79, comun_nom='Quilpué', ciuda_id=21),
        Comuna(comun_id=80, comun_nom='Limache', ciuda_id=21),
        Comuna(comun_id=81, comun_nom='Olmué', ciuda_id=21),
        Comuna(comun_id=82, comun_nom='Villa Alemana', ciuda_id=21),
        Comuna(comun_id=83, comun_nom='Santiago', ciuda_id=22),
        Comuna(comun_id=84, comun_nom='Cerrillos', ciuda_id=22),
        Comuna(comun_id=85, comun_nom='Cerro Navia', ciuda_id=22),
        Comuna(comun_id=86, comun_nom='Conchalí', ciuda_id=22),
        Comuna(comun_id=87, comun_nom='El Bosque', ciuda_id=22),
        Comuna(comun_id=88, comun_nom='Estación Central', ciuda_id=22),
        Comuna(comun_id=89, comun_nom='Huechuraba', ciuda_id=22),
        Comuna(comun_id=90, comun_nom='Independencia', ciuda_id=22),
        Comuna(comun_id=91, comun_nom='La Cisterna', ciuda_id=22),
        Comuna(comun_id=92, comun_nom='La Florida', ciuda_id=22),
        Comuna(comun_id=93, comun_nom='La Granja', ciuda_id=22),
        Comuna(comun_id=94, comun_nom='La Pintana', ciuda_id=22),
        Comuna(comun_id=95, comun_nom='La Reina', ciuda_id=22),
        Comuna(comun_id=96, comun_nom='Las Condes', ciuda_id=22),
        Comuna(comun_id=97, comun_nom='Lo Barnechea', ciuda_id=22),
        Comuna(comun_id=98, comun_nom='Lo Espejo', ciuda_id=22),
        Comuna(comun_id=99, comun_nom='Lo Prado', ciuda_id=22),
        Comuna(comun_id=100, comun_nom='Macul', ciuda_id=22),
        Comuna(comun_id=101, comun_nom='Maipú', ciuda_id=22),
        Comuna(comun_id=102, comun_nom='Ñuñoa', ciuda_id=22),
        Comuna(comun_id=103, comun_nom='Pedro Aguirre Cerda', ciuda_id=22),
        Comuna(comun_id=104, comun_nom='Peñalolén', ciuda_id=22),
        Comuna(comun_id=105, comun_nom='Providencia', ciuda_id=22),
        Comuna(comun_id=106, comun_nom='Pudahuel', ciuda_id=22),
        Comuna(comun_id=107, comun_nom='Quilicura', ciuda_id=22),
        Comuna(comun_id=108, comun_nom='Quinta Normal', ciuda_id=22),
        Comuna(comun_id=109, comun_nom='Recoleta', ciuda_id=22),
        Comuna(comun_id=110, comun_nom='Renca', ciuda_id=22),
        Comuna(comun_id=111, comun_nom='San Joaquín', ciuda_id=22),
        Comuna(comun_id=112, comun_nom='San Miguel', ciuda_id=22),
        Comuna(comun_id=113, comun_nom='San Ramón', ciuda_id=22),
        Comuna(comun_id=114, comun_nom='Vitacura', ciuda_id=22),
        Comuna(comun_id=115, comun_nom='Pirque', ciuda_id=23),
        Comuna(comun_id=116, comun_nom='Puente Alto', ciuda_id=23),
        Comuna(comun_id=117, comun_nom='San José de Maipo', ciuda_id=23),
        Comuna(comun_id=118, comun_nom='Colina', ciuda_id=24),
        Comuna(comun_id=119, comun_nom='Lampa', ciuda_id=24),
        Comuna(comun_id=120, comun_nom='Tiltil', ciuda_id=24),
        Comuna(comun_id=121, comun_nom='Buin', ciuda_id=25),
        Comuna(comun_id=122, comun_nom='Calera de Tango', ciuda_id=25),
        Comuna(comun_id=123, comun_nom='Paine', ciuda_id=25),
        Comuna(comun_id=124, comun_nom='San Bernardo', ciuda_id=22),
        Comuna(comun_id=125, comun_nom='Alhué', ciuda_id=26),
        Comuna(comun_id=126, comun_nom='Curacaví', ciuda_id=26),
        Comuna(comun_id=127, comun_nom='María Pinto', ciuda_id=26),
        Comuna(comun_id=128, comun_nom='Melipilla', ciuda_id=26),
        Comuna(comun_id=129, comun_nom='San Pedro', ciuda_id=26),
        Comuna(comun_id=130, comun_nom='Isla de Maipo', ciuda_id=27),
        Comuna(comun_id=131, comun_nom='El Monte', ciuda_id=27),
        Comuna(comun_id=132, comun_nom='Padre Hurtado', ciuda_id=27),
        Comuna(comun_id=133, comun_nom='Peñaflor', ciuda_id=27),
        Comuna(comun_id=134, comun_nom='Talagante', ciuda_id=27),
        Comuna(comun_id=135, comun_nom='Rancagua', ciuda_id=28),
        Comuna(comun_id=136, comun_nom='Codegua', ciuda_id=28),
        Comuna(comun_id=137, comun_nom='Coinco', ciuda_id=28),
        Comuna(comun_id=138, comun_nom='Coltauco', ciuda_id=28),
        Comuna(comun_id=139, comun_nom='Doñihue', ciuda_id=28),
        Comuna(comun_id=140, comun_nom='Graneros', ciuda_id=28),
        Comuna(comun_id=141, comun_nom='Las Cabras', ciuda_id=28),
        Comuna(comun_id=142, comun_nom='Machalí', ciuda_id=28),
        Comuna(comun_id=143, comun_nom='Malloa', ciuda_id=28),
        Comuna(comun_id=144, comun_nom='Mostazal', ciuda_id=28),
        Comuna(comun_id=145, comun_nom='Olivar', ciuda_id=28),
        Comuna(comun_id=146, comun_nom='Peumo', ciuda_id=28),
        Comuna(comun_id=147, comun_nom='Pichidegua', ciuda_id=28),
        Comuna(comun_id=148, comun_nom='Quinta de Tilcoco', ciuda_id=28),
        Comuna(comun_id=149, comun_nom='Rengo', ciuda_id=28),
        Comuna(comun_id=150, comun_nom='Requínoa', ciuda_id=28),
        Comuna(comun_id=151, comun_nom='San Vicente', ciuda_id=28),
        Comuna(comun_id=152, comun_nom='San Fernando', ciuda_id=29),
        Comuna(comun_id=153, comun_nom='Chépica', ciuda_id=29),
        Comuna(comun_id=154, comun_nom='Chimbarongo', ciuda_id=29),
        Comuna(comun_id=155, comun_nom='Lolol', ciuda_id=29),
        Comuna(comun_id=156, comun_nom='Nancagua', ciuda_id=29),
        Comuna(comun_id=157, comun_nom='Palmilla', ciuda_id=29),
        Comuna(comun_id=158, comun_nom='Peralillo', ciuda_id=29),
        Comuna(comun_id=159, comun_nom='Placilla', ciuda_id=29),
        Comuna(comun_id=160, comun_nom='Pumanque', ciuda_id=29),
        Comuna(comun_id=161, comun_nom='Santa Cruz', ciuda_id=29),
        Comuna(comun_id=162, comun_nom='Pichilemu', ciuda_id=30),
        Comuna(comun_id=163, comun_nom='La Estrella', ciuda_id=30),
        Comuna(comun_id=164, comun_nom='Litueche', ciuda_id=30),
        Comuna(comun_id=165, comun_nom='Marchihue', ciuda_id=30),
        Comuna(comun_id=166, comun_nom='Navidad', ciuda_id=30),
        Comuna(comun_id=167, comun_nom='Paredones', ciuda_id=30),
        Comuna(comun_id=168, comun_nom='Talca', ciuda_id=31),
        Comuna(comun_id=169, comun_nom='Constitución', ciuda_id=31),
        Comuna(comun_id=170, comun_nom='Curepto', ciuda_id=31),
        Comuna(comun_id=171, comun_nom='Empedrado', ciuda_id=31),
        Comuna(comun_id=172, comun_nom='Maule', ciuda_id=31),
        Comuna(comun_id=173, comun_nom='Pelarco', ciuda_id=31),
        Comuna(comun_id=174, comun_nom='Pencahue', ciuda_id=31),
        Comuna(comun_id=175, comun_nom='Río Claro', ciuda_id=31),
        Comuna(comun_id=176, comun_nom='San Clemente', ciuda_id=31),
        Comuna(comun_id=177, comun_nom='San Rafael', ciuda_id=31),
        Comuna(comun_id=178, comun_nom='Cauquenes', ciuda_id=32),
        Comuna(comun_id=179, comun_nom='Chanco', ciuda_id=32),
        Comuna(comun_id=180, comun_nom='Pelluhue', ciuda_id=32),
        Comuna(comun_id=181, comun_nom='Curicó', ciuda_id=33),
        Comuna(comun_id=182, comun_nom='Hualañé', ciuda_id=33),
        Comuna(comun_id=183, comun_nom='Licantén', ciuda_id=33),
        Comuna(comun_id=184, comun_nom='Molina', ciuda_id=33),
        Comuna(comun_id=185, comun_nom='Rauco', ciuda_id=33),
        Comuna(comun_id=186, comun_nom='Romeral', ciuda_id=33),
        Comuna(comun_id=187, comun_nom='Sagrada Familia', ciuda_id=33),
        Comuna(comun_id=188, comun_nom='Teno', ciuda_id=33),
        Comuna(comun_id=189, comun_nom='Vichuquén', ciuda_id=33),
        Comuna(comun_id=190, comun_nom='Linares', ciuda_id=34),
        Comuna(comun_id=191, comun_nom='Colbún', ciuda_id=34),
        Comuna(comun_id=192, comun_nom='Longaví', ciuda_id=34),
        Comuna(comun_id=193, comun_nom='Parral', ciuda_id=34),
        Comuna(comun_id=194, comun_nom='Retiro', ciuda_id=34),
        Comuna(comun_id=195, comun_nom='San Javier', ciuda_id=34),
        Comuna(comun_id=196, comun_nom='Villa Alegre', ciuda_id=34),
        Comuna(comun_id=197, comun_nom='Yerbas Buenas', ciuda_id=34),
        Comuna(comun_id=198, comun_nom='Chillán', ciuda_id=35),
        Comuna(comun_id=199, comun_nom='Bulnes', ciuda_id=35),
        Comuna(comun_id=200, comun_nom='Cobquecura', ciuda_id=35),
        Comuna(comun_id=201, comun_nom='Coelemu', ciuda_id=35),
        Comuna(comun_id=202, comun_nom='Coihueco', ciuda_id=35),
        Comuna(comun_id=203, comun_nom='Chillán Viejo', ciuda_id=35),
        Comuna(comun_id=204, comun_nom='El Carmen', ciuda_id=35),
        Comuna(comun_id=205, comun_nom='Ninhue', ciuda_id=35),
        Comuna(comun_id=206, comun_nom='Ñiquén', ciuda_id=35),
        Comuna(comun_id=207, comun_nom='Pemuco', ciuda_id=35),
        Comuna(comun_id=208, comun_nom='Pinto', ciuda_id=35),
        Comuna(comun_id=209, comun_nom='Quillón', ciuda_id=35),
        Comuna(comun_id=210, comun_nom='San Ignacio', ciuda_id=35),
        Comuna(comun_id=211, comun_nom='San Nicolás', ciuda_id=35),
        Comuna(comun_id=212, comun_nom='Treguaco', ciuda_id=35),
        Comuna(comun_id=213, comun_nom='Yungay', ciuda_id=35),
        Comuna(comun_id=214, comun_nom='Portezuelo', ciuda_id=36),
        Comuna(comun_id=215, comun_nom='Quirihue', ciuda_id=36),
        Comuna(comun_id=216, comun_nom='Ránquil', ciuda_id=36),
        Comuna(comun_id=217, comun_nom='San Fabián', ciuda_id=37),
        Comuna(comun_id=218, comun_nom='San Carlos', ciuda_id=37),
        Comuna(comun_id=219, comun_nom='Concepción', ciuda_id=38),
        Comuna(comun_id=220, comun_nom='Coronel', ciuda_id=38),
        Comuna(comun_id=221, comun_nom='Chiguayante', ciuda_id=38),
        Comuna(comun_id=222, comun_nom='Florida', ciuda_id=38),
        Comuna(comun_id=223, comun_nom='Hualpén', ciuda_id=38),
        Comuna(comun_id=224, comun_nom='Hualqui', ciuda_id=38),
        Comuna(comun_id=225, comun_nom='Lota', ciuda_id=38),
        Comuna(comun_id=226, comun_nom='Penco', ciuda_id=38),
        Comuna(comun_id=227, comun_nom='San Pedro de la Paz', ciuda_id=38),
        Comuna(comun_id=228, comun_nom='Santa Juana', ciuda_id=38),
        Comuna(comun_id=229, comun_nom='Talcahuano', ciuda_id=38),
        Comuna(comun_id=230, comun_nom='Tomé', ciuda_id=38),
        Comuna(comun_id=231, comun_nom='Lebu', ciuda_id=39),
        Comuna(comun_id=232, comun_nom='Arauco', ciuda_id=39),
        Comuna(comun_id=233, comun_nom='Cañete', ciuda_id=39),
        Comuna(comun_id=234, comun_nom='Contulmo', ciuda_id=39),
        Comuna(comun_id=235, comun_nom='Curanilahue', ciuda_id=39),
        Comuna(comun_id=236, comun_nom='Los Álamos', ciuda_id=39),
        Comuna(comun_id=237, comun_nom='Tirúa', ciuda_id=39),
        Comuna(comun_id=238, comun_nom='Los Ángeles', ciuda_id=40),
        Comuna(comun_id=239, comun_nom='Antuco', ciuda_id=40),
        Comuna(comun_id=240, comun_nom='Cabrero', ciuda_id=40),
        Comuna(comun_id=241, comun_nom='Laja', ciuda_id=40),
        Comuna(comun_id=242, comun_nom='Mulchén', ciuda_id=40),
        Comuna(comun_id=243, comun_nom='Nacimiento', ciuda_id=40),
        Comuna(comun_id=244, comun_nom='Negrete', ciuda_id=40),
        Comuna(comun_id=245, comun_nom='Quilaco', ciuda_id=40),
        Comuna(comun_id=246, comun_nom='Quilleco', ciuda_id=40),
        Comuna(comun_id=247, comun_nom='San Rosendo', ciuda_id=40),
        Comuna(comun_id=248, comun_nom='Santa Bárbara', ciuda_id=40),
        Comuna(comun_id=249, comun_nom='Tucapel', ciuda_id=40),
        Comuna(comun_id=250, comun_nom='Yumbel', ciuda_id=40),
        Comuna(comun_id=251, comun_nom='Alto Biobío', ciuda_id=40),
        Comuna(comun_id=252, comun_nom='Temuco', ciuda_id=41),
        Comuna(comun_id=253, comun_nom='Carahue', ciuda_id=41),
        Comuna(comun_id=254, comun_nom='Cunco', ciuda_id=41),
        Comuna(comun_id=255, comun_nom='Curarrehue', ciuda_id=41),
        Comuna(comun_id=256, comun_nom='Freire', ciuda_id=41),
        Comuna(comun_id=257, comun_nom='Galvarino', ciuda_id=41),
        Comuna(comun_id=258, comun_nom='Gorbea', ciuda_id=41),
        Comuna(comun_id=259, comun_nom='Lautaro', ciuda_id=41),
        Comuna(comun_id=260, comun_nom='Cholchol', ciuda_id=41),
        Comuna(comun_id=261, comun_nom='Loncoche', ciuda_id=41),
        Comuna(comun_id=262, comun_nom='Melipeuco', ciuda_id=41),
        Comuna(comun_id=263, comun_nom='Nueva Imperial', ciuda_id=41),
        Comuna(comun_id=264, comun_nom='Padre Las Casas', ciuda_id=41),
        Comuna(comun_id=265, comun_nom='Perquenco', ciuda_id=41),
        Comuna(comun_id=266, comun_nom='Pitrufquén', ciuda_id=41),
        Comuna(comun_id=267, comun_nom='Pucón', ciuda_id=41),
        Comuna(comun_id=268, comun_nom='Saavedra', ciuda_id=41),
        Comuna(comun_id=269, comun_nom='Teodoro Schmidt', ciuda_id=41),
        Comuna(comun_id=270, comun_nom='Toltén', ciuda_id=41),
        Comuna(comun_id=271, comun_nom='Vilcún', ciuda_id=41),
        Comuna(comun_id=272, comun_nom='Villarrica', ciuda_id=41),
        Comuna(comun_id=273, comun_nom='Angol', ciuda_id=42),
        Comuna(comun_id=274, comun_nom='Collipulli', ciuda_id=42),
        Comuna(comun_id=275, comun_nom='Curacautín', ciuda_id=42),
        Comuna(comun_id=276, comun_nom='Ercilla', ciuda_id=42),
        Comuna(comun_id=277, comun_nom='Lonquimay', ciuda_id=42),
        Comuna(comun_id=278, comun_nom='Los Sauces', ciuda_id=42),
        Comuna(comun_id=279, comun_nom='Lumaco', ciuda_id=42),
        Comuna(comun_id=280, comun_nom='Purén', ciuda_id=42),
        Comuna(comun_id=281, comun_nom='Renaico', ciuda_id=42),
        Comuna(comun_id=282, comun_nom='Traiguén', ciuda_id=42),
        Comuna(comun_id=283, comun_nom='Victoria', ciuda_id=42),
        Comuna(comun_id=284, comun_nom='Valdivia', ciuda_id=43),
        Comuna(comun_id=285, comun_nom='Corral', ciuda_id=43),
        Comuna(comun_id=286, comun_nom='Lanco', ciuda_id=43),
        Comuna(comun_id=287, comun_nom='Los Lagos', ciuda_id=43),
        Comuna(comun_id=288, comun_nom='Máfil', ciuda_id=43),
        Comuna(comun_id=289, comun_nom='Mariquina', ciuda_id=43),
        Comuna(comun_id=290, comun_nom='Paillaco', ciuda_id=43),
        Comuna(comun_id=291, comun_nom='Panguipulli', ciuda_id=43),
        Comuna(comun_id=292, comun_nom='La Unión', ciuda_id=44),
        Comuna(comun_id=293, comun_nom='Futrono', ciuda_id=44),
        Comuna(comun_id=294, comun_nom='Lago Ranco', ciuda_id=44),
        Comuna(comun_id=295, comun_nom='Río Bueno', ciuda_id=44),
        Comuna(comun_id=296, comun_nom='Puerto Montt', ciuda_id=45),
        Comuna(comun_id=297, comun_nom='Calbuco', ciuda_id=45),
        Comuna(comun_id=298, comun_nom='Cochamó', ciuda_id=45),
        Comuna(comun_id=299, comun_nom='Fresia', ciuda_id=45),
        Comuna(comun_id=300, comun_nom='Frutillar', ciuda_id=45),
        Comuna(comun_id=301, comun_nom='Los Muermos', ciuda_id=45),
        Comuna(comun_id=302, comun_nom='Llanquihue', ciuda_id=45),
        Comuna(comun_id=303, comun_nom='Maullín', ciuda_id=45),
        Comuna(comun_id=304, comun_nom='Puerto Varas', ciuda_id=45),
        Comuna(comun_id=305, comun_nom='Castro', ciuda_id=46),
        Comuna(comun_id=306, comun_nom='Ancud', ciuda_id=46),
        Comuna(comun_id=307, comun_nom='Chonchi', ciuda_id=46),
        Comuna(comun_id=308, comun_nom='Curaco de Vélez', ciuda_id=46),
        Comuna(comun_id=309, comun_nom='Dalcahue', ciuda_id=46),
        Comuna(comun_id=310, comun_nom='Puqueldón', ciuda_id=46),
        Comuna(comun_id=311, comun_nom='Queilén', ciuda_id=46),
        Comuna(comun_id=312, comun_nom='Quellón', ciuda_id=46),
        Comuna(comun_id=313, comun_nom='Quemchi', ciuda_id=46),
        Comuna(comun_id=314, comun_nom='Quinchao', ciuda_id=46),
        Comuna(comun_id=315, comun_nom='Osorno', ciuda_id=47),
        Comuna(comun_id=316, comun_nom='Puerto Octay', ciuda_id=47),
        Comuna(comun_id=317, comun_nom='Purranque', ciuda_id=47),
        Comuna(comun_id=318, comun_nom='Puyehue', ciuda_id=47),
        Comuna(comun_id=319, comun_nom='Río Negro', ciuda_id=47),
        Comuna(comun_id=320, comun_nom='San Pablo', ciuda_id=47),
        Comuna(comun_id=321, comun_nom='San Juan de la Costa', ciuda_id=47),
        Comuna(comun_id=322, comun_nom='Chaitén', ciuda_id=48),
        Comuna(comun_id=323, comun_nom='Futaleufú', ciuda_id=48),
        Comuna(comun_id=324, comun_nom='Hualaihué', ciuda_id=48),
        Comuna(comun_id=325, comun_nom='Palena', ciuda_id=48),
        Comuna(comun_id=326, comun_nom='Coyhaique', ciuda_id=49),
        Comuna(comun_id=327, comun_nom='Lago Verde', ciuda_id=49),
        Comuna(comun_id=328, comun_nom='Aysén', ciuda_id=50),
        Comuna(comun_id=329, comun_nom='Cisnes', ciuda_id=50),
        Comuna(comun_id=330, comun_nom='Guaitecas', ciuda_id=50),
        Comuna(comun_id=331, comun_nom='Cochrane', ciuda_id=51),
        Comuna(comun_id=332, comun_nom="O'Higgins", ciuda_id=51),
        Comuna(comun_id=333, comun_nom='Tortel', ciuda_id=51),
        Comuna(comun_id=334, comun_nom='Chile Chico', ciuda_id=52),
        Comuna(comun_id=335, comun_nom='Río Ibáñez', ciuda_id=52),
        Comuna(comun_id=336, comun_nom='Punta Arenas', ciuda_id=53),
        Comuna(comun_id=337, comun_nom='Laguna Blanca', ciuda_id=53),
        Comuna(comun_id=338, comun_nom='Río Verde', ciuda_id=53),
        Comuna(comun_id=339, comun_nom='San Gregorio', ciuda_id=53),
        Comuna(comun_id=340, comun_nom='Cabo de Hornos', ciuda_id=54),
        Comuna(comun_id=341, comun_nom='Antártica', ciuda_id=54),
        Comuna(comun_id=342, comun_nom='Porvenir', ciuda_id=55),
        Comuna(comun_id=343, comun_nom='Primavera', ciuda_id=55),
        Comuna(comun_id=344, comun_nom='Timaukel', ciuda_id=55),
        Comuna(comun_id=345, comun_nom='Puerto Natales', ciuda_id=56),
        Comuna(comun_id=346, comun_nom='Torres del Paine', ciuda_id=56),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('DireccionApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
