# Generated by Django 4.2 on 2025-11-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proye_idt', models.AutoField(primary_key=True, serialize=False)),
                ('proye_desc', models.CharField(max_length=200)),
                ('proye_obs', models.TextField(blank=True, null=True)),
                ('proye_estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('proye_fecha_sol', models.DateField()),
                ('proye_fecha_ter', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
    ]
