# Generated by Django 4.2 on 2025-11-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmpresaPersonaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proye_idt', models.AutoField(primary_key=True, serialize=False)),
                ('proye_desc', models.CharField(max_length=200)),
                ('proye_obs', models.TextField(blank=True, null=True)),
                ('proye_estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('proye_fecha_sol', models.DateField()),
                ('proye_fecha_ter', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='EmpresaPersonaApp.empresapersona')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
    ]
