# Generated by Django 4.2.16 on 2025-12-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('password_visible', models.CharField(help_text='Almacena la contraseña en texto plano para visualización del administrador.', max_length=128)),
                ('email', models.EmailField(blank=True, help_text='Correo asociado al usuario para recuperación de contraseña.', max_length=254, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('contador', 'Contador')], default='contador', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario de sistema',
                'verbose_name_plural': 'Usuarios de sistema',
                'db_table': 'USUARIO_SISTEMA',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to='UsuariosApp.usuariosistema')),
            ],
            options={
                'verbose_name': 'Código de recuperación',
                'verbose_name_plural': 'Códigos de recuperación',
                'db_table': 'PASSWORD_RESET_CODE',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
