# Generated by Django 4.2 on 2025-12-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('password_visible', models.CharField(help_text='Almacena la contraseña en texto plano para visualización del administrador.', max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('contador', 'Contador')], default='contador', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario de sistema',
                'verbose_name_plural': 'Usuarios de sistema',
                'db_table': 'USUARIO_SISTEMA',
            },
        ),
    ]
