# Generated by Django 4.2 on 2025-12-04 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosistema',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo asociado al usuario para recuperación de contraseña.', max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to='UsuariosApp.usuariosistema')),
            ],
            options={
                'verbose_name': 'Código de recuperación',
                'verbose_name_plural': 'Códigos de recuperación',
                'db_table': 'PASSWORD_RESET_CODE',
            },
        ),
    ]
