# Generated by Django 4.2.16 on 2025-12-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacturacionApp', '0002_seed_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledoc',
            name='dedoc_pagado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
