-- Create
CREATE TABLE TIPO_TRANSACCION (
    TIPO_ID INT,
    TIPO_TRANS VARCHAR(20),
    PRIMARY KEY(TIPO_ID)
);

CREATE TABLE TIPO_DOCUMENTO (
    TIDOC_ID INT,
    TIDOC_TIPO VARCHAR(20),
    PRIMARY KEY(TIDOC_ID)
);

CREATE TABLE TIPO_PAGO (
    TPAGO_ID INT,
    TPAGO_TIPO VARCHAR(20),
    PRIMARY KEY(TPAGO_ID)
);

CREATE TABLE TRANSACCION (
    TRANS_ID INT,
    DOCUM_NUM INT,
    TIPO_ID INT,
    TRANS_FECHA DATE,
    TRANS_MONTO INT,
    PRIMARY KEY(TRANS_ID, TIPO_ID, DOCUM_NUM),
    FOREIGN KEY(TIPO_ID) REFERENCES TIPO_TRANSACCION(TIPO_ID),
    FOREIGN KEY(DOCUM_NUM) REFERENCES DOCUMENTO(DOCUM_NUM),
    FOREIGN KEY(PROYE_IDT) REFERENCES PROYECTO(PROYE_IDT)
);

CREATE TABLE DOCUMENTO (
    DOCUM_NUM INT,
    DOCUM_ESTADO VARCHAR(20),
    EMPPE_ID INT,
    PROYE_IDT INT,
    TIDOC_ID INT,
    DOCUM_FECHA_EMI DATE,
    DOCUM_FECHA_VEN DATE,
    DOCUM_FECHA_RECL DATE,
    DOCUM_OBS VARCHAR(200),
    FPAGO_ID INT,
    PRIMARY KEY(DOCUM_NUM),
    FOREIGN KEY(EMPPE_ID) REFERENCES EMPRESAPERSONA(EMPPE_ID),
    FOREIGN KEY(PROYE_IDT) REFERENCES PROYECTO(PROYE_IDT),
    FOREIGN KEY(TIDOC_ID) REFERENCES TIPO_DOCUMENTO(TIDOC_ID),
    FOREIGN KEY(FPAGO_ID) REFERENCES FORMA_PAGO(FPAGO_ID)
);

CREATE TABLE DETALLE_DOC (
    DOCUM_NUM INT,
    PRODU_ID INT,
    DEDOC_CANT INT,
    DEDOC_OBS VARCHAR(200),
    PRIMARY KEY(DOCUM_NUM, PRODU_ID),
    FOREIGN KEY(DOCUM_NUM) REFERENCES DOCUMENTO(DOCUM_NUM),
    FOREIGN KEY(PRODU_ID) REFERENCES PRODUCTOS_SERVICIOS(PRODU_ID)
);

CREATE TABLE FORMA_PAGO (
    FPAGO_ID INT,
    TPAGO_ID INT,
    FPAGO_DIAS INT,
    PRIMARY KEY(FPAGO_ID),
    FOREIGN KEY(TPAGO_ID) REFERENCES TIPO_PAGO(TPAGO_ID)
);


-- Insert tablas 2
INSERT INTO TIPO_TRANSACCION (TIPO_ID, TIPO_TRANS) VALUES
    (1, 'INGRESO'),
    (2, 'EGRESO');

INSERT INTO TIPO_DOCUMENTO (TIDOC_ID, TIDOC_TIPO) VALUES
    (1, 'FACTURA'),
    (2, 'BOLETA'),
    (3, 'NOTA DE CREDITO'),
    (4, 'ORDEN DE COMPRA');

INSERT INTO TIPO_PAGO (TPAGO_ID, TPAGO_TIPO) VALUES
    (1, 'EFECTIVO'),
    (2, 'TARJETA DE CREDITO'),
    (3, 'TRANSFERENCIA BANCARIA'),
    (4, 'CHEQUE'),
    (5, 'PAGARE'),
    (6, 'MIXTO');